import mysql.connector
import tkinter as tk
from tkinter import messagebox
def log_in():
    user = a.get()
    pass_w = b.get()
    if user == "" or pass_w == "":
        messagebox.showerror("Error", "Please enter both username and password")
        return
    s = mysql.connector.connect(user="root", password="kali", host="localhost", database="login_details")
    c1 = s.cursor()
    c1.execute("SELECT * FROM users WHERE username=%s AND password=%s", (user, pass_w))
    c2 = c1.fetchone()
    s.close()
    if c2:
        messagebox.showinfo("Login success", "Welcome " + user)
        open_window()
    else:
        messagebox.showerror("Login Failed", "Invalid username or password")
def open_window():
    new = tk.Toplevel()
    new.title("Personal Details")
    new.geometry("1080x580")
    l3 = tk.Label(new, text="Personal Details Page", fg="red", bg="black", font=("Arial", 14, "bold"))
    l3.grid(row=0, column=0, columnspan=2, padx=400, pady=10)
    l4 = tk.Label(new, text="Name of Applicant:")
    l4.grid(row=1, column=0, pady=10)
    e3 = tk.Entry(new)
    e3.grid(row=1, column=1, pady=10)
    l5 = tk.Label(new, text="Mobile No:")
    l5.grid(row=2, column=0, pady=10)
    e4 = tk.Entry(new)
    e4.grid(row=2, column=1, pady=10)
    l6 = tk.Label(new, text="Alternate Mobile No:")
    l6.grid(row=3, column=0, pady=10)
    e5 = tk.Entry(new)
    e5.grid(row=3, column=1, pady=10)
    l7 = tk.Label(new, text="Address:")
    l7.grid(row=4, column=0, pady=10)
    e6 = tk.Entry(new)
    e6.grid(row=4, column=1, pady=10)
    l8 = tk.Label(new, text="Submission Date (YYYY-MM-DD):")
    l8.grid(row=5, column=0, pady=10)
    e7 = tk.Entry(new)
    e7.grid(row=5, column=1, pady=10)
    l10 = tk.Label(new, text="Return Date (YYYY-MM-DD):")
    l10.grid(row=6, column=0, pady=10)
    e9 = tk.Entry(new)
    e9.grid(row=6, column=1, pady=10)
    def submit_details():
        name = e3.get()
        mobile = e4.get()
        alternate_mobile = e5.get()
        address = e6.get()
        submission_date = e7.get()
        return_date = e9.get()
        if name == "" or mobile == "" or address == "" or submission_date == "" or return_date == "":
            messagebox.showerror("Error", "Please fill all fields")
            return
        s = mysql.connector.connect(user="root", password="kali", host="localhost", database="login_details")
        c = s.cursor()
        c.execute("INSERT INTO personal_details (name, mobile_no, alt_mobile_no, address, submission_date, return_date) VALUES (%s, %s, %s, %s, %s, %s)",
                  (name, mobile, alternate_mobile, address, submission_date, return_date))
        s.commit()
        s.close()
        messagebox.showinfo("Success", "Details Submitted!")
        open_car_details_window(submission_date, return_date)
    b2 = tk.Button(new, text="Submit",fg="black", bg="green", font=("Arial", 12), command=submit_details)
    b2.grid(row=7, column=0, columnspan=2, pady=20)
def open_car_details_window(submission_date, return_date):
    car_win = tk.Toplevel()
    car_win.title("Car Details")
    car_win.geometry("500x350")
    l1 = tk.Label(car_win, text="Car Details",fg="red",bg="black",font=("Arial", 14, "bold"))
    l1.grid(row=0, column=0, columnspan=2, pady=10)
    l2 = tk.Label(car_win, text="Car Number:", font=("Arial", 12))
    l2.grid(row=1, column=0, padx=10, pady=10)
    e1 = tk.Entry(car_win, font=("Arial", 12))
    e1.grid(row=1, column=1, padx=10, pady=10)
    l3 = tk.Label(car_win, text="Car Company:", font=("Arial", 12))
    l3.grid(row=2, column=0, padx=10, pady=10)
    e2 = tk.Entry(car_win, font=("Arial", 12))
    e2.grid(row=2, column=1, padx=10, pady=10)
    l4 = tk.Label(car_win, text="Car Model:", font=("Arial", 12))
    l4.grid(row=3, column=0, padx=10, pady=10)
    e3 = tk.Entry(car_win, font=("Arial", 12))
    e3.grid(row=3, column=1, padx=10, pady=10)
    def submit_car_details():
        car_number = e1.get()
        company = e2.get()
        model = e3.get()
        if car_number == "" or company == "" or model == "":
            messagebox.showerror("Error", "Please fill all car details")
            return
        d = mysql.connector.connect(user="root", password="kali", host="localhost", database="login_details")
        c = d.cursor()
        c.execute("INSERT INTO car_details (car_number, company, model) VALUES (%s, %s, %s)",
                    (car_number, company, model))
        d.commit()
        d.close()
        messagebox.showinfo("Success", "Car details submitted successfully!")
        open_payment_window(submission_date, return_date)
    b1 = tk.Button(car_win, text="Submit", font=("Arial", 12),fg="black",bg="green", command=submit_car_details)
    b1.grid(row=4, column=0, columnspan=2, pady=20)
def open_payment_window(submission_date, return_date):
    n1 = tk.Toplevel()
    n1.title("Payment Window")
    n1.geometry("500x300")
    l1 = tk.Label(n1, text="Payment Details",fg="red",bg="black",font=("Arial", 14, "bold"))
    l1.grid(row=0, column=0, columnspan=2, pady=10)
    l2=tk.Label(n1, text="Submission Date:")
    l2.grid(row=1, column=0, padx=10, pady=5)
    l3=tk.Label(n1, text=submission_date)
    l3.grid(row=1, column=1, padx=10, pady=5)
    l4=tk.Label(n1, text="Return Date:")
    l4.grid(row=2, column=0, padx=10, pady=5)
    l5=tk.Label(n1, text=return_date)
    l5.grid(row=2, column=1, padx=10, pady=5)
    l6=tk.Label(n1, text="Enter Total Amount (₹):")
    l6.grid(row=3, column=0, padx=10, pady=10)
    e1 = tk.Entry(n1)
    e1.grid(row=3, column=1, padx=10, pady=10)
    def confirm_payment():
        amount = e1.get()
        if amount == "":
            messagebox.showerror("Error", "Please enter the amount")
            return
        s = mysql.connector.connect(user="root", password="kali", host="localhost", database="login_details")
        c = s.cursor()
        c.execute("INSERT INTO payment_details (submission_date, return_date, total_amount) VALUES (%s, %s, %s)",
                  (submission_date, return_date, amount))
        s.commit()
        s.close()
        messagebox.showinfo("Success", "Payment details saved successfully!")
        print("PROGRAM IS EXECUTED SUCCESSFULLY")
    b1 = tk.Button(n1, text="Submit Payment", font=("Arial", 12),fg="black",bg="green", command=confirm_payment)
    b1.grid(row=4, column=0, columnspan=2, pady=20)
w = tk.Tk()
w.title("Login Window")
w.geometry("500x300")
l = tk.Label(w, text="LOGIN PAGE", fg="red", bg="black", font=("Arial", 16, "bold"))
l.grid(row=0, column=0, columnspan=2, padx=120, pady=20)
l1 = tk.Label(w, text="Username:", font=("Arial", 12))
l1.grid(row=1, column=0, padx=10, pady=10)
a = tk.StringVar()
e = tk.Entry(w, textvariable=a, font=("Arial", 12))
e.grid(row=1, column=1, padx=10, pady=10)
l2 = tk.Label(w, text="Password:", font=("Arial", 12))
l2.grid(row=2, column=0, padx=10, pady=10)
b = tk.StringVar()
e1 = tk.Entry(w, textvariable=b, show="*", font=("Arial", 12))
e1.grid(row=2, column=1, padx=10, pady=10)
b1 = tk.Button(w, text="Login", font=("Arial", 12, "bold"), fg="black", bg="green", command=log_in)
b1.grid(row=3, column=0, columnspan=2, pady=20)
w.mainloop()

